#!/usr/bin/env python3
"""Generate BEM orientation files from ADDA '-orient avg' parameter files.

The point placement follows ADDA's crosssec.c ScanIntegrParms:
  * alpha/gamma: equally spaced in angle;
  * beta: equally spaced in cos(beta);
  * equival=true removes the duplicated max endpoint from the stored angle set.

The non-adaptive Jmax weights are generated by applying ADDA's normalized
Romberg/trapezoid rule to 1D basis vectors.  The output is compatible with
BEM-CUDA --orient-file: alpha_deg beta_deg gamma_deg weight.
"""

import argparse
import math
import re
from collections import namedtuple
from pathlib import Path
from typing import Dict, List, Tuple


Axis = namedtuple(
    "Axis",
    "name min_deg max_deg jmin jmax eps equival periodic cos_space values weights",
)


def parse_bool(text: str) -> bool:
    if text == "true":
        return True
    if text == "false":
        return False
    raise ValueError(f"expected true/false, got {text!r}")


def parse_axis(text: str, name: str, cos_space: bool) -> Axis:
    m = re.search(rf"^{name}:\s*(.*?)(?=^[a-z]+:|\Z)", text, flags=re.M | re.S)
    if not m:
        raise ValueError(f"section {name}: not found")
    sec = m.group(1)

    def value(key: str) -> str:
        mm = re.search(rf"^\s*{re.escape(key)}\s*=\s*([^\s#]+)", sec, flags=re.M)
        if not mm:
            raise ValueError(f"section {name}: missing {key}=")
        return mm.group(1)

    min_deg = float(value("min"))
    max_deg = float(value("max"))
    jmin = int(value("Jmin"))
    jmax = int(value("Jmax"))
    eps = float(value("eps"))
    equival = parse_bool(value("equiv"))
    periodic = parse_bool(value("periodic"))
    values, grid_size = axis_values(min_deg, max_deg, jmax, equival, cos_space)
    weights = romberg_1d_weights(grid_size, jmax, equival, periodic)
    if len(values) != len(weights):
        raise RuntimeError(f"{name}: {len(values)} values but {len(weights)} weights")
    return Axis(name, min_deg, max_deg, jmin, jmax, eps, equival, periodic, cos_space, values, weights)


def axis_values(min_deg: float, max_deg: float, jmax: int, equival: bool, cos_space: bool) -> Tuple[List[float], int]:
    if min_deg == max_deg:
        return [min_deg], 1
    grid_size = (1 << jmax) + 1
    n = grid_size - 1 if equival and grid_size > 1 else grid_size
    if cos_space:
        lo = math.cos(math.radians(max_deg))
        hi = math.cos(math.radians(min_deg))
        step = (hi - lo) / (grid_size - 1)
        vals = [math.degrees(math.acos(max(-1.0, min(1.0, lo + step * i)))) for i in range(n)]
    else:
        step = (max_deg - min_deg) / (grid_size - 1)
        vals = [min_deg + step * i for i in range(n)]
    return vals, grid_size


def romberg_1d_weights(grid_size: int, jmax: int, equival: bool, periodic: bool) -> List[float]:
    """ADDA Romberg1D weights for a normalized average over one axis."""
    if grid_size == 1:
        return [1.0]
    n_data = grid_size - 1 if equival and grid_size > 1 else grid_size
    weights = []
    for idx in range(n_data):
        data = [0.0] * n_data
        data[idx] = 1.0
        weights.append(romberg_1d_value(data, grid_size, jmax, equival, periodic))
    s = sum(weights)
    if s == 0:
        raise RuntimeError("zero Romberg weight sum")
    return [w / s for w in weights]


def romberg_1d_value(data: List[float], grid_size: int, jmax: int, equival: bool, periodic: bool) -> float:
    """Literal scalar version of ADDA Romberg1D for non-adaptive Jmax."""
    if grid_size == 1:
        return data[0]
    msize = 0 if periodic else jmax
    m1 = [0.0] * (msize + 1)
    t1 = 0.0
    tv1 = [1.0] * (max(msize + 1, 1))
    tv2 = [0.0] * (max(msize + 1, 1))
    tv3 = [0.0] * (max(msize + 1, 1))
    if msize:
        for i in range(1, msize):
            tv1[i] = tv1[i - 1] * 4.0
            tv2[i] = 1.0 / (tv1[i] - 1.0)
            tv3[i - 1] = 2.0 * tv1[i - 1] - 1.0
    for m in range(jmax):
        if m == 0:
            if equival:
                t1 = data[0]
            else:
                t1 = 0.5 * (data[0] + data[(grid_size - 1)])
            m0 = 0
        else:
            if periodic:
                t1 = 0.5 * (t1 + m1[0])
                m0 = 0
            else:
                t1 = tv3[m - 1] * tv2[m] * (t1 - m1[0]) + m1[0]
                m0 = m
        step = (grid_size - 1) >> m
        acc = 0.0
        j = step >> 1
        while j < grid_size:
            acc += data[j]
            j += step
        m1[m0] = acc * (2.0 ** (-m))
        if m0 != 0:
            for i in range(m - 1, -1, -1):
                m1[i] = tv2[m - i] * (tv1[m - i] * m1[i + 1] - m1[i])
    return 0.5 * (m1[0] + t1)


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("avg_file", type=Path)
    ap.add_argument("--out", type=Path, required=True)
    ap.add_argument("--bg-out", type=Path,
                    help="Also write beta_deg gamma_deg weight for BEM --orient-bg-file with --alpha-avg")
    ap.add_argument("--summary", type=Path)
    ap.add_argument("--no-collapse-poles", action="store_true",
                    help="Do not merge gamma samples at beta=0/180 for full-alpha averages")
    args = ap.parse_args()

    text = args.avg_file.read_text()
    alpha = parse_axis(text, "alpha", cos_space=False)
    beta = parse_axis(text, "beta", cos_space=True)
    gamma = parse_axis(text, "gamma", cos_space=False)

    full_alpha_range = abs((alpha.max_deg - alpha.min_deg) - 360.0) < 1e-10
    rows: Dict[Tuple[float, float, float], float] = {}
    bg_rows: Dict[Tuple[float, float], float] = {}
    raw_total = 0
    args.out.parent.mkdir(parents=True, exist_ok=True)
    for a, wa in zip(alpha.values, alpha.weights):
        for b, wb in zip(beta.values, beta.weights):
            pole = full_alpha_range and (abs(b - beta.min_deg) < 1e-10 or abs(b - beta.max_deg) < 1e-10)
            for g, wg in zip(gamma.values, gamma.weights):
                raw_total += 1
                gout = 0.0 if pole and not args.no_collapse_poles else g
                key = (a, b, gout)
                rows[key] = rows.get(key, 0.0) + wa * wb * wg
                bg_key = (b, gout)
                bg_rows[bg_key] = bg_rows.get(bg_key, 0.0) + wb * wg

    weight_sum = sum(rows.values())
    with args.out.open("w") as f:
        f.write("# alpha_deg beta_deg gamma_deg weight\n")
        f.write(f"# generated from {args.avg_file}\n")
        for (a, b, g), w in rows.items():
            f.write(f"{a:.17g} {b:.17g} {g:.17g} {w:.17g}\n")
    if args.bg_out:
        args.bg_out.parent.mkdir(parents=True, exist_ok=True)
        bg_sum = sum(bg_rows.values())
        with args.bg_out.open("w") as f:
            f.write("# beta_deg gamma_deg weight\n")
            f.write(f"# generated from {args.avg_file}; use with --alpha-avg {len(alpha.values)}\n")
            for (b, g), w in bg_rows.items():
                f.write(f"{b:.17g} {g:.17g} {w / bg_sum:.17g}\n")

    summary = (
        f"alpha N={len(alpha.values)} J={alpha.jmax} periodic={alpha.periodic} equival={alpha.equival}\n"
        f"beta  N={len(beta.values)} J={beta.jmax} periodic={beta.periodic} equival={beta.equival} cos_space=true\n"
        f"gamma N={len(gamma.values)} J={gamma.jmax} periodic={gamma.periodic} equival={gamma.equival}\n"
        f"raw_product_orientations={raw_total}\n"
        f"orientations={len(rows)}\n"
        f"beta_gamma_orientations={len(bg_rows)}\n"
        f"recommended_alpha_avg={len(alpha.values)}\n"
        f"collapsed_beta_poles={full_alpha_range and not args.no_collapse_poles}\n"
        f"weight_sum={weight_sum:.17g}\n"
    )
    if args.summary:
        args.summary.parent.mkdir(parents=True, exist_ok=True)
        args.summary.write_text(summary)
    print(summary, end="")


if __name__ == "__main__":
    main()
