#!/usr/bin/env python3
"""Inventory verified raw ADDA outputs from log/mueller pairs."""

import argparse
import csv
import re
from collections import defaultdict
from pathlib import Path


PATTERNS = {
    "version": re.compile(r"Generated by ADDA\s+(.+)"),
    "command": re.compile(r"command:\s+'(.+)'"),
    "shape": re.compile(r"shape:\s+specified by file\s+(.+?)\s+-\s+(.+?);\s+size along x-axis:\s+([0-9eE+.-]+)"),
    "ri": re.compile(r"refractive index:\s+(.+)"),
    "dpl": re.compile(r"Dipoles/lambda:\s+([0-9eE+.-]+)"),
    "dipoles": re.compile(r"Total number of occupied dipoles:\s+([0-9]+)"),
    "veq": re.compile(r"Volume-equivalent size parameter:\s+([0-9eE+.-]+)"),
    "box": re.compile(r"box dimensions:\s+(.+)"),
}


def parse_log(path):
    result = {}
    text = path.read_text(errors="replace")
    for key, pattern in PATTERNS.items():
        match = pattern.search(text)
        if match:
            if key == "shape":
                result["shape_file"] = match.group(1)
                result["shape_format"] = match.group(2)
                result["shape_x"] = match.group(3)
            else:
                result[key] = match.group(1)
    if "version" not in result:
        return None
    return result


def orientation_key(run_dir, root):
    rel = run_dir.relative_to(root)
    if len(rel.parts) <= 1:
        return "."
    return str(Path(*rel.parts[:-1]))


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("roots", nargs="+", type=Path)
    parser.add_argument("--out", required=True, type=Path)
    args = parser.parse_args()

    groups = {}
    for root in args.roots:
        root = root.resolve()
        for log in root.rglob("log"):
            run_dir = log.parent
            if not (run_dir / "mueller").exists():
                continue
            info = parse_log(log)
            if info is None:
                continue
            key = (
                str(root),
                orientation_key(run_dir, root),
                info.get("shape_file", ""),
                info.get("ri", ""),
                info.get("dpl", ""),
                info.get("veq", ""),
                info.get("dipoles", ""),
            )
            entry = groups.setdefault(key, {
                "root": str(root),
                "set": orientation_key(run_dir, root),
                "shape_file": info.get("shape_file", ""),
                "shape_format": info.get("shape_format", ""),
                "shape_x": info.get("shape_x", ""),
                "ri": info.get("ri", ""),
                "dpl": info.get("dpl", ""),
                "dipoles": info.get("dipoles", ""),
                "veq": info.get("veq", ""),
                "box": info.get("box", ""),
                "version": info.get("version", ""),
                "count": 0,
                "example": str(run_dir),
            })
            entry["count"] += 1

    rows = sorted(groups.values(), key=lambda r: (
        r["root"], r["set"], float(r["veq"] or "nan"), r["shape_file"]))
    args.out.parent.mkdir(parents=True, exist_ok=True)
    fields = [
        "root", "set", "count", "veq", "ri", "dpl", "dipoles", "box",
        "shape_file", "shape_x", "shape_format", "version", "example",
    ]
    with args.out.open("w", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=fields)
        writer.writeheader()
        writer.writerows(rows)
    print(f"wrote {len(rows)} ADDA sets to {args.out}")
    by_shape = defaultdict(int)
    for row in rows:
        by_shape[row["shape_file"]] += row["count"]
    for shape, count in sorted(by_shape.items(), key=lambda item: (-item[1], item[0]))[:20]:
        print(f"{count:5d} {shape}")


if __name__ == "__main__":
    main()
